spring:
  application:
    name: Proofread

backend:
  menus:
    - name: "Dashboard"
      url: "/backend/dashboard"
      icon: "tachometer-alt"
    - name: "Empty"
      url: "/backend/empty"
      icon: "square"