spring:
  application:
    name: My Blog

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/iae-blog?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:secret_mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #generate-ddl: true
    show-sql: true

  mail:
    host: ${MAIL_HOST:localhost}
    port: 1025

backend:
  menus:
    - name: "Dashboard"
      url: "/backend/dashboard"
      icon: "tachometer-alt"
    - name: "Empty"
      url: "/backend/empty"
      icon: "square"
    - name: Users
      url: /backend/users
      icon: users
    - name: "Posts"
      url: "/backend/posts"
      icon: "file-alt"